# SQL Interview Questions  - Quiz

## Introduction

In this lesson, we'll go through a short quiz containing the types of questions about SQL and relational databases that you can expect to see in an interview. 



## SQL Interview Questions

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

what are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

Type your answer below this line:
_______________________________________________________________________________________________________________________________

1. TEXT
2. INTEGER
3. REAL
4. BLOB

As for using data types found in other popular SQL engines, it is possible to use some of them since the data types found in SQLite3 are really data type *categories*.  So, when using a type from another engine - provided SQLite3 understands the *name* of the data type - SQLite3 simply coerces into the appropriate category.  This again depends on whether SQLite3 "understands" the name of the data type to be used (from other SQL database engines).




## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Type your answer below this line:
_______________________________________________________________________________________________________________________________

Primary and Foreign keys are used to establish JOIN relationships between two tables, to form set theoretic concatenation of columns from two different tables.  The Primary key is the key in the table containing the data to be included in the result set.  While the foreign key contains a reference (value) to the primary key, in order to relate or associate data (columns) in the second table back to the first table.



## Question 3

Explain the different types of relationships entities can have in a SQL database. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________

1. one-to-many
2. many-to-many

In a one-to-many relationship, many records in the secondary table of a join can be associated with a single record in the primary table.  An example would be: a single customer can have (potentially) many orders.



## Question 4

Explain the various types of JOINs possible with SQL. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________

Joins can be thought of in terms of set-theoretic operations, where rows in tables are considered the sets involved.

There exist the following types of joins:

1. **INNER**: this type of join corresponds to the INTERSECTION set-theoretic operation, wherein only records with equal values of the columns referenced in the join condition are in included in the result set; that is, a value (of the referenced columns) must be include in both tables - e.g. table1 AND table2.
2. **OUTER**: suppose there are two tables involved in the join - i.e. table1 and table2; then the resultset in this type of join will include ALL records from table 1 (the "left" table) and ONLY those records from table2 where the values from the columns referenced in the join condition are equal; when no record exists in the "right" table (table2) with a value from the columns referenced in the join condition, then the result set has the value NULL for for that row of the right table (table2).
    1. **LEFT**: this is described in **OUTER**, above
    2. **RIGHT**: an outer join where all records from the right table (table2) are included and only those from the left table wherein the values from the columns referenced in the join condition are equal; when no record exists in the left table (table1) with a value from the columns referenced in the join condition, then the result set has the value NULL for for that row of the left table (table1).
3. **FULL**: ALL records from both tables are included; this can be combined with INNER/OUTER
    1. **FULL INNER**: only records where column values referenced in the join condition are included
    2. **FULL OUTER**: a record is include if its value is in either the left OR the right table
4. **CARTESIAN PRODUCT**: this is also known as the CROSS PRODUCT - each record from the left table with value in the join condition is matched to each record of the right table corresponding to a value in the join condition; so if there are $m$ records in the left table and $n$ records in the right table, there there will be $m \times n$ records in the result set.


## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

Type your answer below this line:
_______________________________________________________________________________________________________________________________

Aggregate functions perform some operation on the set of aggregated values produced by the GROUP BY condition.  The aggregate function returns a scalar value computed on the aggregated values.  For example, we can compute the average of aggregated values of (hypothetical) *quantityOrdered* but we must use a grouping semantic which tell us *how* to collected aggregated values.


## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?


Type your answer below this line:
_______________________________________________________________________________________________________________________________

A many-to-many INNER join is just the CARTESIAN PRODUCT - i.e. each record from the left table with value in the join condition is matched to each record of the right table corresponding to a value in the join condition; so if there are $m$ records in the left table and $n$ records in the right table, there there will be $m \times n$ records in the result set.

This is even more complicated for a many-to-many OUTER join since records from either table having values not equal are also included and paired (joined).


## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.